Fix regression / syntax error for Python 2.7
Fix regression / syntax error for Python 2.7 introduced on commit https://github.com/jaraco/zipp/commit/3d17ee58654a24e8578f7979d7019e0f41ca060b

```
  File "/home/fox/git/botoform/.env/lib/python2.7/site-packages/importlib_resources-3.3.0-py2.7.egg/importlib_resources/_compat.py", line 48, in <module>
    from zipp import Path as ZipPath  # type: ignore
  File "/home/fox/git/botoform/.env/lib/python2.7/site-packages/zipp-3.4.0-py2.7.egg/zipp.py", line 240
    def open(self, mode='r', *args, pwd=None, **kwargs):
                                      ^
SyntaxError: invalid syntax
```